nginx:
 dockerfile: ./Dockerfile # путь до докер файла указываем относительно директории в build
 build: ./contaners/nginx
 restart: always
 ports:
  - "8089:81"
 volumes:
  - ./logs:/etc/logs/nginx
 volumes_from:
  - fpm:rw
 environment:
  - NGINX_HOST=localhost
  - NGINX_PORT=81
 command: nginx -g "daemon off;" # Можно было указать в докер-фале, но можно и здесь)
 links:
  - fpm
fpm:
 image: fobia/php
 # dockerfile: ./Dockerfile
 # build: ./contaners/fpm
 volumes:
  - ./php-code:/var/www:rw
  - ./php-code/hulq-mscan:/var/www/hulq-mscan:rw
 links:
  - memcached

memcached:
 image: memcached
 ports:
  - 11211:11211 # Проброс портов для внешнего доступа
